
language: node_js

node_js:
    - "node"
    - "11"
    - "10"


sudo: false

git:
    submodules: false

before_script:
    - npm install
    - npm build

script:
    - npm start
    - npm run test-command

